version: "3.7"
services:
  opentelemetry-collector:
    build:
      context: ~/go/src/github.com/tmc/opentelemetry-collector
    environment:
      GOOGLE_SERVICE_ACCOUNT_KEY: Cg==
      #CONFIG_TEMPLATE: otel.local.yaml
    ports:
      - "55678:55678"
      - "55679:55679"
      - "8889:8889"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  jaeger:
    image: jaegertracing/all-in-one:1.17
    ports:
      - "14250:14250"
      - "16686:16686"
