#!/bin/bash
set -euo pipefail
if [ "${GOOGLE_SERVICE_ACCOUNT_KEY}" != "" ]; then
  echo "${GOOGLE_SERVICE_ACCOUNT_KEY}" | base64 -d > gcp-creds.json
  export GOOGLE_APPLICATION_CREDENTIALS=gcp-creds.json
fi

PROJECT_ID="${PROJECT_ID:-default-project-id}"

# Render otel.yaml
echo '# Code generated by entrypoint.sh. DO NOT EDIT.' > otel.yaml
eval "cat <<EOF
$(<${CONFIG_TEMPLATE:-otel.yaml.in})
EOF
" >> otel.yaml

cat otel.yaml
otelcol --log-level=DEBUG --config otel.yaml

